https-portal:
  image: tenrero/https-tls-testtool
  ports:
    - '80:80'
    - '443:443'
  environment:
    DOMAINS: 'domain.com'
    DEBUG: 'true'
    ERROR_LOG: stdout
    ACCESS_LOG: stderr  
    # STAGE: 'production' # Don't use production until staging works
